// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Dias Utekin",
            "email": "dias.utekin@nu.edu.kz"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/students": {
            "get": {
                "description": "Get all students",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "GetStudents Get all students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Studio56School_university_internal_model.Student"
                            }
                        }
                    }
                }
            }
        },
        "/students/create": {
            "post": {
                "description": "Create Student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "CreateStudent",
                "operationId": "create-student",
                "parameters": [
                    {
                        "description": "create account",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Studio56School_university_internal_model.Student"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Studio56School_university_internal_model.Student"
                        }
                    }
                }
            }
        },
        "/students/{id}": {
            "get": {
                "description": "Get student by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "GetStudentsById",
                "operationId": "get-student",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Studio56School_university_internal_model.Student"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "DeleteStudent",
                "operationId": "delete-student",
                "responses": {
                    "200": {
                        "description": "Successful deleted user with id",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Studio56School_university_internal_model.Student": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string",
                    "example": "F"
                },
                "name": {
                    "type": "string",
                    "example": "Madina"
                },
                "surname": {
                    "type": "string",
                    "example": "Akhmetova"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ec2-18-192-183-17.eu-central-1.compute.amazonaws.com:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "University app",
	Description:      "This is a sample server of University project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
